name: Build and Submit to App Stores

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
  APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
  APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
  APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
  GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

jobs:
  build-and-submit:
    name: Build and Submit
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up App Store Connect API Key
        if: env.APP_STORE_CONNECT_KEY != ''
        run: |
          mkdir -p ~/private_keys
          echo "$APP_STORE_CONNECT_KEY" > ~/private_keys/AuthKey_${{ env.APP_STORE_CONNECT_KEY_IDENTIFIER }}.p8
          echo "APP_STORE_CONNECT_KEY_PATH=~/private_keys/AuthKey_${{ env.APP_STORE_CONNECT_KEY_IDENTIFIER }}.p8" >> $GITHUB_ENV

      - name: Set up Google Service Account Key
        if: env.GOOGLE_SERVICE_ACCOUNT_KEY != ''
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > google-service-account-key.json
          echo "GOOGLE_SERVICE_ACCOUNT_KEY_BASE64=$(base64 -i google-service-account-key.json | tr -d '\n')" >> $GITHUB_ENV

      - name: Login to Expo
        run: eas login --non-interactive --token ${{ env.EXPO_TOKEN }}

      - name: Install EAS
        run: npm install -g eas-cli

      - name: Build iOS
        run: eas build --platform ios --non-interactive --no-wait --profile production

      - name: Build Android
        run: eas build --platform android --non-interactive --no-wait --profile production

      - name: Submit to App Store Connect
        if: success() && github.ref == 'refs/heads/main' && env.APPLE_ID != ''
        run: eas submit --platform ios --non-interactive --no-wait --profile production

      - name: Submit to Google Play
        if: success() && github.ref == 'refs/heads/main' && env.GOOGLE_SERVICE_ACCOUNT_KEY != ''
        run: eas submit --platform android --non-interactive --no-wait --profile production

      - name: Update App Store Metadata
        if: success() && github.ref == 'refs/heads/main' && env.APPLE_ID != ''
        run: |
          eas metadata:push
