name: EAS Build and Submit

on:
  push:
    branches: [main, staging]
    paths:
      - '**'
      - '!.github/workflows/**'
  pull_request:
    branches: [main, staging]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build for'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - production

env:
  NODE_VERSION: '18.x'
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  
  # iOS App Store Connect
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
  APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
  APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
  APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
  APP_STORE_CONNECT_APP_ID: ${{ secrets.APP_STORE_CONNECT_APP_ID }}
  APP_SKU: ${{ secrets.APP_SKU }}
  APP_COMPANY_NAME: ${{ secrets.APP_COMPANY_NAME }}
  APP_DISPLAY_NAME: ${{ secrets.APP_DISPLAY_NAME }}
  
  # Google Play
  GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
  GOOGLE_PLAY_TRACK: ${{ github.ref == 'refs/heads/main' && 'internal' || 'internal' }}

jobs:
  build-and-submit:
    name: Build and Submit
    runs-on: macos-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up credentials directory
        run: |
          mkdir -p ./credentials
          echo "CREDENTIALS_DIR=$(pwd)/credentials" >> $GITHUB_ENV

      - name: Set up App Store Connect API Key
        if: ${{ env.APP_STORE_CONNECT_KEY != '' }}
        run: |
          echo "${{ env.APP_STORE_CONNECT_KEY }}" > $CREDENTIALS_DIR/AuthKey_${{ env.APP_STORE_CONNECT_KEY_IDENTIFIER }}.p8
          echo "APP_STORE_CONNECT_KEY_PATH=$CREDENTIALS_DIR/AuthKey_${{ env.APP_STORE_CONNECT_KEY_IDENTIFIER }}.p8" >> $GITHUB_ENV
          echo "ASC_KEY_ID=${{ env.APP_STORE_CONNECT_KEY_IDENTIFIER }}" >> $GITHUB_ENV
          echo "ASC_ISSUER_ID=${{ env.APP_STORE_CONNECT_ISSUER_ID }}" >> $GITHUB_ENV

      - name: Set up Google Service Account Key
        if: ${{ env.GOOGLE_SERVICE_ACCOUNT_KEY != '' }}
        run: |
          echo "${{ env.GOOGLE_SERVICE_ACCOUNT_KEY }}" > $CREDENTIALS_DIR/google-service-account-key.json
          echo "GOOGLE_SERVICE_ACCOUNT_KEY_PATH=$CREDENTIALS_DIR/google-service-account-key.json" >> $GITHUB_ENV

      - name: Login to Expo
        run: eas login --non-interactive --token ${{ env.EXPO_TOKEN }}

      - name: Configure EAS
        run: |
          echo "EXPO_ENV=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref == 'refs/heads/main' && 'production' || 'preview' }}" >> $GITHUB_ENV
          echo "BUILD_PROFILE=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref == 'refs/heads/main' && 'production' || 'preview' }}" >> $GITHUB_ENV

      - name: Build app
        run: |
          if [ "$BUILD_PROFILE" = "production" ]; then
            eas build --platform all --non-interactive --no-wait --profile $BUILD_PROFILE
          else
            eas build --platform all --non-interactive --no-wait --profile $BUILD_PROFILE
          fi
        env:
          EAS_NO_VCS: 1
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Submit to stores (Production only)
        if: ${{ github.ref == 'refs/heads/main' && env.BUILD_PROFILE == 'production' }}
        run: |
          # Submit to App Store Connect
          if [ -n "$APPLE_ID" ]; then
            eas submit --platform ios --non-interactive --no-wait --profile production
          fi
          
          # Submit to Google Play
          if [ -n "$GOOGLE_SERVICE_ACCOUNT_KEY" ]; then
            eas submit --platform android --non-interactive --no-wait --profile production
          fi

      - name: Update App Store Metadata (Production only)
        if: ${{ github.ref == 'refs/heads/main' && env.BUILD_PROFILE == 'production' && env.APPLE_ID != '' }}
        run: |
          eas metadata:push --profile production

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            $CREDENTIALS_DIR
            *.apk
            *.aab
            *.ipa
            *.plist
          retention-days: 7

      - name: Post build cleanup
        if: always()
        run: |
          # Remove sensitive files
          rm -rf $CREDENTIALS_DIR
          rm -f *.apk *.aab *.ipa *.plist
